[JR-AVL-987] Adicionado opção de token como autenticação
clicksign/convertapi-ruby-clicksign pull request #1
Opened 2024-07-12 12:38 UTC by GabrielLima1

### Descrição

Atualmente na utilização da `gem convert_api`, só temos a opção de se autenticar utilizando a `api_secret`, porém isso faz com que tenhamos uma unica `secret`, para todos os ambientes (`dev, staging, sandbox` e `prod`), o que é bem ruim.

A ideia do PR, é ajustar a autenticação fornecida pela gem, para conseguirmos nos autenticar com o `token` e não via `api_secret`, dessa forma, cada ambiente terá sua autenticação;

### Issue tracker

Card do [Jira](https://clicksign.atlassian.net/browse/AVL-987).

### Code Review

Como fazer o Code Review:

[CONTRIBUTING.md](https://github.com/clicksign/.github/blob/8d623c886c2da0266d108d5fa21cf01a1c82cbc0/CONTRIBUTING.md)

### Checklist para poder mergear

- [ ] O código do PR inclui (ou já possui) testes para o código nele
- [ ] Os checks de linters estão passando
- [ ] Os checks de testes estão passando

2024-07-12 13:49 UTC, FernandoSacchet requested changes

2024-07-12 13:49 UTC, FernandoSacchet commented on lib/convert_api/client.rb
> +      raise(TokenError, 'Token not configured') if config.token.nil?
A ideia não seria sobrescrever o que existe e sim manter as duas alternativas.
Dessa forma acredito que eles não irão aceitar o merge e teríamos que manter para sempre o fork.

2024-07-12 13:51 UTC, GabrielLima1 commented on lib/convert_api/client.rb
> +      raise(TokenError, 'Token not configured') if config.token.nil?
Boua, vou ajustar

2024-07-12 16:39 UTC, GabrielLima1 commented on lib/convert_api/client.rb
> +      raise(TokenError, 'Token not configured') if config.token.nil?
Ajustei para utilizar o `token` ou o `secret`, dependendo do que foi configurado... e a `exception` para ser mais flexível.

2024-07-15 17:26 UTC, FernandoSacchet approved these changes

2024-07-15 17:47 UTC, merged